remove validation to test how linter handles input

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,51 +25,40 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - uses: actions/checkout@v4
-    - name: Validate file patterns
-      run: |
-        SUPPORTED_EXTENSIONS="js jsx tsx html vue md markdown"
-        PATTERN_INPUT="${{ inputs.files_pattern }}"
-        # Split multiline input into an array of lines
-        IFS=$'\n' read -r -d '' -a PATTERNS <<< "$PATTERN_INPUT"
-
-        for pattern in "${PATTERNS[@]}"; do
-          # Check for negated patterns
-          if [[ "$pattern" =~ ^! ]]; then
-            echo "Skipping negated pattern: $pattern"
-            continue
-          fi
-
-          # Detect brace expansion and handle it
-          if [[ "$pattern" =~ \{.*?\} ]]; then
-            # Extract braces content and split by commas
-            BRACE_CONTENT="${pattern##*\{}"
-            BRACE_CONTENT="${BRACE_CONTENT%%\}*}"
-            IFS=',' read -r -a EXTENSIONS <<< "$BRACE_CONTENT"
-
-            for EXTENSION in "${EXTENSIONS[@]}"; do
-              # Check if the extension is in the list of supported extensions
-              if [[ ! " $SUPPORTED_EXTENSIONS " =~ " $EXTENSION " ]]; then
-                echo "::error::Unsupported file extension detected: $EXTENSION in pattern $pattern"
-                exit 1
-              fi
-            done
-          else
-            # Handle patterns without braces separately, extract extension
-            EXTENSION="${pattern##*.}"
-            # In case there's no clearer ".ext" part, we should skip it
-            if [[ "$EXTENSION" == "$pattern" ]]; then
-              echo "Skipping pattern without clear extension: $pattern"
-              continue
-            fi
-            # Check if the extension is in the list of supported extensions
-            if [[ ! " $SUPPORTED_EXTENSIONS " =~ " $EXTENSION " ]]; then
-              echo "::error::Unsupported file extension detected: $EXTENSION in pattern $pattern"
-              exit 1
-            fi
-          fi
-        done
-      shell: bash
+    # - uses: actions/checkout@v4
+    # - name: Validate file patterns
+    #   run: |
+    #     SUPPORTED_EXTENSIONS="js jsx tsx html vue md markdown"
+    #     PATTERN_INPUT="${{ inputs.files_pattern }}"
+    #     echo "Checking input: $PATTERN_INPUT"
+    #     # Split patterns into an array
+    #     IFS=$'\n' read -r -d '' -a PATTERNS <<< "$(echo "$PATTERN_INPUT" | xargs -n1)"
+    #     for pattern in "${PATTERNS[@]}"; do
+    #           echo "Checking array: $pattern"
+    #     done
+    #     for pattern in "${PATTERNS[@]}"; do
+    #       echo "Checking pattern: $pattern"
+    #       # Extract the extension from the pattern
+    #       EXTENSION="${pattern##*.}"
+    #       echo "Checking extension: $EXTENSION"
+    #       NEXT_CHAR="${EXTENSION:0:1}"
+    #         echo "Next character in extension: $NEXT_CHAR"
+    #         if [[ "$NEXT_CHAR" == "{" ]]; then
+    #         NEW_EXTENSION="${pattern#*\{}"
+    #         NEW_EXTENSION="${NEW_EXTENSION%\}*}"
+    #         echo "Checking extension: $NEW_EXTENSION"
+    #           IFS=',' read -r -a PATTERNS1 <<< "$NEW_EXTENSION"
+    #           for pattern1 in "${PATTERNS1[@]}"; do
+    #             echo "Checking extension: $pattern1"
+    #             # Check if the extension is in the list of supported extensions
+    #             if [[ ! " $SUPPORTED_EXTENSIONS " =~ " $pattern1 " ]]; then
+    #               echo "::error::Unsupported file extension detected: $pattern1"
+    #           exit 1
+    #           fi
+    #           done
+    #         fi
+    #     done
+    #   shell: bash
     - uses: mikefarah/yq@master
     - name: Get changed files
       id: changed_files
